# Generated by Django 4.1.7 on 2023-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_discription_todo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=232)),
                ('days', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='todousername',
            field=models.ManyToManyField(to='todo.user'),
        ),
        migrations.AddField(
            model_name='todo',
            name='todoproject',
            field=models.ManyToManyField(to='todo.project'),
        ),
    ]
